name: heart
channels:
  - conda-forge
  - defaults
dependencies:
  - arm_pyart
  - cartopy
  - jupyter
  - jupyterlab
  - holoviews
  - geopandas
  - goes2go
  - bokeh
  - numpy
  - pandas
  - python
  - xarray
  - netcdf4
  - dask
  - lxml
  - bottleneck
  - scikit-learn
  - matplotlib
  - metpy
  - seaborn
  - h5py
  - fsspec
  - s3fs
  - toml
  - zarr
  - distributed
  - beautifulsoup4
  - h5netcdf
  - scipy
  - xmitgcm
prefix: C:\Users\gentemann\Miniconda3\envs\heart